<title>DwaneWeb - Ontwerp</title>

	<link href="style_eendag_ontwerp.css" rel="stylesheet" type="text/css">
	
					<header>
						<h2 class="mainpageh2">Ontwerp</h2>
					</header>

					<footer>
						<p class="post-info">DwaneWeb - 2021</p>
					</footer> 
				<div class="mainheader2">
				<a href="IMAGES/screenshot1vergroot.JPG"  border="0" target="_blank" title="Screenshot 1 van de werkende website.">
					<img src="IMAGES/screenshot1.JPG" border="0" target="_blank" title="Screenshot 1 van de werkende website."></a>
				<a href="IMAGES/screenshot2vergroot.JPG"  border="0" target="_blank" title="Screenshot 2 van de werkende website.">
					<img src="IMAGES/screenshot2.JPG" border="0" target="_blank" title="Screenshot 2 van de werkende website."></a>
				</div>
			</div>
