<title>DwaneWeb - Opdrachten</title>

	<link href="style_opdrachten.css" rel="stylesheet" type="text/css">

					<header>
						<h2 class="mainpageh2">Opdrachten</h2>
					</header>

					<footer>
						<p class="post-info">DwaneWeb - 2021</p>
					</footer> 
				<div class="mainheader2">
			<hr>
		<a href="IMAGES/opdracht1vergroot.jpg"  border="0" target="_blank" title="Opdracht: AND-poort (EN)">
			<img src="IMAGES/opdracht1.jpg" border="0" target="_blank" title="Opdracht: AND-poort (EN)"></a>
			<hr>
			<a href="IMAGES/logohuisvergroot.PNG"  border="0" target="_blank" title="Opdracht: Huis in Logo">
				<img src="IMAGES/logohuis.PNG" border="0" target="_blank" title="Opdracht: Huis in Logo"></a>
				<a href="IMAGES/huisschetsvergroot.JPG"  border="0" target="_blank" title="Opdracht: Schets het huis">
					<img src="IMAGES/huisschets.JPG" border="0" target="_blank" title="Opdracht: Schets het huis"></a>
					<a href="IMAGES/huisvergroot.jpg"  border="0" target="_blank" title="Opdracht: Foto van het huis">
						<img src="IMAGES/huis.jpg" border="0" target="_blank" title="Opdracht: Foto van het huis"></a>
						<div class="mainheader2link">
							<p>Hier is de <a href="logocode.inc" target="_blank">code</a> voor het huis.</p>
						</div>
				</div>
			<hr>
			</div>
